/**:
  ros__parameters:
    #NTRIP Params
    ntrip_ip: "212.156.70.42"
    ntrip_user_name: "..........."
    ntrip_password: "......"
    ntrip_mount_point: "VRSRTCM31"
    ntrip_port: 2101

    #NTRIP Location Params
    set_ntrip_location_from_yaml: false
    nav_sat_fix_topic: "/sensing/gnss/clap/ros/gps_nav_sat_fix" #if set_ntrip_location_from_yaml false
    ntrip_location_lat: 40.1740978  #if set_ntrip_location_active true
    ntrip_location_lon: 28.7735008  #if set_ntrip_location_active true

    #Serial Port Params
    publish_port_rtcm_active: false
    serial_port: "/dev/ttyUSB0"
    serial_port_baud_rate: 460800

    #RTCM Publisher Params
    publish_ros_rtcm_active: true
    rtcm_topic: "/sensing/gnss/ntrip/rtcm"


    debug: true


